### ISSUE TITLE
DISCUSSION: Master(s), compute nodes, interactive nodes, login nodes, nodes with internet access, ...

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-HPC/pilot-testing#2]
Summary:

* master(s)
  - running scheduler, admin tasks, etc.

* compute nodes
  - not accessible by other means than running jobs.
  - no internet access.
  - no build capabilities.

* login node(s)
  - no outgoing internet access.
  - to submit and query jobs.

* interactive node(s)
  - internet access.
  - to build and install software.
  - to prototype and test job scripts.

(The previous topic in this thread changed into a discussion on what type of nodes and what web access they have.  Moving the notes on missing software to another thread.)

**Comment by jlbl** [comment]
I assume the *pdf* stuff is only needed on the interactive node, not the compute nodes, right?

**Comment by HenrikBengtsson** [comment]
jlbl wrote on Feb 14:
> I assume the *pdf* stuff is only needed on the interactive node, not the compute nodes, right?

Although I discovered this by running `R CMD check`, `pdflatex` and all of LaTeX can certainly be needed by other software for generating PDF reports on the fly.  So, I think they can be useful also on the nodes.

For now, although it's useful if you add them, you can also just keep eye out here and I can reach out to your whenever I / we hit real show stoppers.

**Comment by jlbl** [comment]
On Tue, 14 Feb 2017 at 2:07pm, Henrik Bengtsson wrote

>> I assume the *pdf* stuff is only needed on the interactive node, not 
>> the compute nodes, right?
>
> Although I discovered this by running `R CMD check`, `pdflatex` and all 
> of LaTeX can certainly be needed by other software for generating PDF 
> reports on the fly.  So, I think they can be useful also on the nodes.
>
> For now, although it's useful if you add them, you can also just keep 
> eye out here and I can reach out to your whenever I / we hit real show 
> stoppers.

Ah, I see what's going on.  Since it was initally meant as a simple job 
submission node, qb3-login1 started with a fairly minimal software load. 
Some things (e.g. compilers) have been added since the initial setup, but 
it's been piecemeal.  What qb3-login1 doesn't have is the complete set of 
software that's on the compute nodes.  In this case, R isn't there.  If it 
was, it would have already dragged in large chunks of texlive (including 
pdflatex), just like on the nodes.

In general I like keeping the login node separate from the compile/testing 
node.  Should we just combine them here and for now, and separate them out 
in the refactoring?

-- 
Joshua Baker-LePain
QB3 Shared Cluster Sysadmin
UCSF

**Comment by HenrikBengtsson** [comment]
Now I also understand (I'm used to a cluster where the compute nodes have literally identical setups as the master / head node).

It would certainly be useful to have an interactive node that have _identical setup_ as the compute nodes (but then also with internet access so you can install things as you need).  This way you can prototype things to make sure that things will work before you submit them as jobs.

BTW, on TORQUE / PBS, one can do `qsub -I` to request an interactive job (gives you a command-line on one of the nodes).  Is that possible under SGE?

**Comment by jlbl** [comment]
On Tue, 14 Feb 2017 at 2:39pm, Henrik Bengtsson wrote

> Now I also understand (I'm used to a cluster where the compute nodes 
> have literally identical setups as the master / head node).
>
> It would certainly be useful to have an interactive node that have 
> _identical setup_ as the compute nodes (but then also with internet 
> access so you can install things as you need).  This way you can 
> prototype things to make sure that things will work before you submit 
> them as jobs.

I like to separate that from the login node so that one person's "testing" 
(which goes awry, eats up all the memory, and crashes the interactive 
node) doesn't interfere with everybody else's job script editing and 
submissions.

> BTW, on TORQUE / PBS, one can do `qsub -I` to request an interactive job 
> (gives you a command-line on one of the nodes).  Is that possible under 
> SGE?

It is, but we keep it disabled for a couple of reasons:

1) It's potentially a wasted core, since the interactive session uses up a
    slot but certainly won't keep the core busy all the time.

2) Some groups strenuously object to direct logins to compute nodes, to
    the extent that they insist that any host users can directly get a
    shell on not mount their storage.  Yes, it's nonsensical, since
    anything you can do interactively you can do in a job script.  Yes,
    this has been explained to them.  Yes, they still insist on the
    distinction.

-- 
Joshua Baker-LePain
QB3 Shared Cluster Sysadmin
UCSF

**Comment by HenrikBengtsson** [comment]
> I like to separate that from the login node so that one person's "testing" (which goes awry, eats up all the memory, and crashes the interactive node) doesn't interfere with everybody else's job script editing and submissions.

So, it sounds like we need:
 * master(s) - running scheduler etc.
 * compute nodes - not accessible by other means than running jobs.
 * login node(s) - to submit and check jobs.
 * interactive node(s): to prototype and test job scripts, install software, etc.  From the users' perspective, these should be configured identical to the compute nodes except that they'll also have internet access.

> 2) Some groups strenuously object to direct logins to compute nodes, to the extent that they insist that any host users can directly get a shell on not mount their storage.  Yes, it's nonsensical, since anything you can do interactively you can do in a job script.  Yes, this has been explained to them.  Yes, they still insist on the distinction.

I hear you - being able to see a mount point in an interactive session doesn't mean you have any access to it.   So, this should be added the list of "user requirements".   Not sure if it's easily done, but one could imagine to _not_ meet this requirement when starting out with this cluster and then only add back later when those groups would like to join and can argue for it, i.e. this discuss could be taken later.
